// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgmsxypqpcbvarkehkdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnbXN4eXBxcGNidmFya2Voa2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzYwNzksImV4cCI6MjA3MDMxMjA3OX0.KWLaUAK1ABBn4LSoro1rEt9Nna0BcD4A0SBbXOZgmbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});